# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56e0eab13eb2a8e106dfc6e9565e8d264ac7bc1b06f461bde3160c63f29648ddc7d9f80f421abd5047b313b26062fffdae22e84f3f3e1bf43cb35fc187a2dd9d

test:
  secret_key_base: 3ee540b65f1e680f1f6efc61f6e96b9f1ba572eeea13a111dcfe8c5733b53d1316966ef1977ddf5df439003e83e24cc87f1e35c7942d07cb7b41cadb815ef4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
